### ISSUE TITLE
FfmTerminalProvider fails in GraalVM native image despite downcall registration

### ISSUE THREAD

**Issue by stalep** [aeshell/aesh-readline#253]
## Problem

`FfmTerminalProvider` fails in GraalVM native images with `Failed to initialize FfmPty`, even when:
- FFM downcall signatures are registered via GraalVM reachability metadata
- `--enable-native-access=ALL-UNNAMED` is passed to native-image
- `LibC`, `PosixConstants`, and `FfmPty` are deferred to runtime initialization
- `FfmPty` is registered for reflection

The fallback to `ExecPtyTerminalProvider` works correctly (prompt, tab completion, raw mode all work), so this is not blocking. But FFM would provide better performance (no `stty` process spawning) and the poll-based read loop that enables clean exit.

## Environment

- GraalVM CE / Mandrel JDK 25 (builder image: `quay.io/quarkus/ubi10-quarkus-mandrel-builder-image:jdk-25`)
- Quarkus 999-SNAPSHOT with explicit `FfmDowncallBuildItem` registration for all LibC functions
- Linux x86_64

## Log Output

```
Found supported terminal provider: ffm (priority=100)
Provider ffm failed: Failed to initialize FfmPty
Created terminal using provider: exec
```

The full exception is caught and only the message is logged. The root cause needs investigation — it could be:
- FFM `Linker.nativeLinker()` not working in native image
- Multi-release JAR class loading issue (`FfmPty` is in `META-INF/versions/22/`)
- `captureCallState` or `firstVariadicArg` linker options not supported in native image
- Missing symbol lookup in the native image's libc binding

## Related

- aesh-readline#250 — flush fix for ExecPty fallback path
- aesh-readline#252 — double-Enter exit issue with ExecPty's blocking read loop

**Comment by stalep** [comment]
**Root cause identified:** The FFM failure in native image is caused by `LibC`'s static initializer failing when running under **Mandrel** (the default Quarkus native image builder, `ubi10-quarkus-mandrel-builder-image:jdk-25`).

The `NoClassDefFoundError: Could not initialize class org.aesh.terminal.tty.impl.LibC` indicates that `Linker.nativeLinker().downcallHandle()` calls in LibC's static init block are failing at runtime in Mandrel's native image, despite:
- FFM downcall signatures being registered via GraalVM reachability metadata
- `--enable-native-access=ALL-UNNAMED` being passed
- `LibC` being deferred to runtime initialization

Full stack trace:
```
java.io.IOException: Failed to initialize FfmPty
    at org.aesh.terminal.tty.impl.FfmPty.<init>(FfmPty.java:146)
    at org.aesh.terminal.tty.impl.FfmPty.current(FfmPty.java:99)
    at org.aesh.terminal.tty.provider.FfmTerminalProvider.createTerminal(FfmTerminalProvider.java:73)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.aesh.terminal.tty.impl.LibC
    at org.aesh.terminal.tty.impl.FfmPty.<init>(FfmPty.java:114)
```

This may be a Mandrel-specific limitation. Testing with GraalVM CE could yield different results. The ExecPty fallback works correctly with aesh-readline 3.17, so this is not blocking.
